Update DEFAULT_ARGS to replace deprecated value with current supported value
runtastic/rubocop_runner pull request #7
Opened 2022-05-27 14:10 UTC by gregfletch

Rubocop 1.30.0 deprecated `auto-correct` as an argument and changed to `autocorrect` (see https://github.com/rubocop/rubocop/blob/master/CHANGELOG.md). This change updates the `rubocop_runner` default arguments to use the current value (i.e. `autocorrect`) to eliminate deprecation warnings when the pre-commit hook runs.

2022-10-06 12:24 UTC, Goltergaul commented
Hi thank you for your pull request, just saw it now. I have another open that might make this obsolete though

2022-10-06 13:20 UTC, Goltergaul requested changes
Thank you for your PR, to keep backwards compatibility i'd suggest to use -a instead of --autocorrect

2022-10-06 13:20 UTC, Goltergaul commented on lib/rubocop_runner.rb
> -  DEFAULT_ARGS = %w[--auto-correct
this does not work with older versions of rubocop. But i think we could get around this by specifying the option as `-a` instead

2022-10-06 14:22 UTC, gregfletch commented on lib/rubocop_runner.rb
> -  DEFAULT_ARGS = %w[--auto-correct
Done, thanks for reviewing and the feedback.

2022-10-07 06:37 UTC, Goltergaul approved these changes

2022-10-07 06:41 UTC, TheWudu approved these changes

2022-10-07 07:01 UTC, ThomasKoppensteiner approved these changes

2022-10-07 07:28 UTC, ThomasKoppensteiner commented
This PR will fix #8

2022-10-07 07:59 UTC, merged